name: CI

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setting up python
        uses: actions/setup-python@v3
        with:
          python-versiono: '3.11'

      - name: Installing dependencies
        run: pip install -r requirements.txt
        
      - name: Applying migrations
        run: python manage.py migrate
        
      - name: Running tests
        run: python manage.py test
